services: 
  app: 
    build: .
    container_name: events-app
    volumes:
      - ./:/web_app
    ports: 
      - 5000:5000
    environment: 
      - FLASK_ENV=developement
    command: python3 -u run.py